encoder_kwargs:
    dims: [1000, 1000, 100]   # encoder and decoder have three mlp layers:[512, 300, 100]
    norm: True              # wether ues normalization in the mlp layers
    norm_type: batchnorm    # normalize type. use batchnorm or layernorm
    dropout: False 
    dropout_p: 0.2  
learning_rate: 0.001
weight_decay: 0.0001
covariate_specific_theta: False 
kl_weight: 5e-4
noise_rate: 0.1

